---

# Travis configuration

dist: 'trusty'
sudo: 'required'

services:
  - 'docker'

language: 'python'

env:
  matrix:
    - TOXENV='py27-ansible24'
    - TOXENV='py27-ansible25'
    - TOXENV='py27-ansible26'
    - TOXENV='py27-ansible27'

before_install:
  # Create SSH keys
  - cat /dev/zero | ssh-keygen -q -N ""
install:
  - 'pip install tox-travis'

script:
  - 'tox -e "${TOXENV}"'

notifications:
  webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
