---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "account-management-docker-centos7"
    groups:
      - 'centos'
    image: 'jrei/systemd-centos:7'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "account-management-docker-centos8"
    groups:
      - 'centos'
    image: 'jrei/systemd-centos:8'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "account-management-docker-debian9"
    groups:
      - 'debian'
    image: 'jrei/systemd-debian:9'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "account-management-docker-debian10"
    groups:
      - 'debian'
    image: 'jrei/systemd-debian:10'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "account-management-docker-ubuntu18"
    groups:
      - 'ubuntu'
    image: 'jrei/systemd-ubuntu:18.04'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "account-management-docker-ubuntu20"
    groups:
      - 'ubuntu'
    image: 'jrei/systemd-ubuntu:20.04'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
provisioner:
  name: 'ansible'
  inventory:
    group_vars:
      all:
        account_management_groups:
          - name: 'my-group'
            gid: 1500
            state: 'absent'
            is_system: True
          - name: 'my-group2'
            gid: 1500
            state: 'present'
            is_system: True
          - name: 'my-user3'
            gid: 1501
            state: 'present'
            is_system: True
        account_management_users:
          - name: 'my-user'
            state: 'absent'
          - name: 'my-user2'
            state: 'present'
          - name: 'my-user3'
            append: False
            comment: 'Foobar'
            createhome: True
            home_mode: '0755'
            home_group: 'my-group2'
            group: 'my-user3'
            groups:
              - 'my-group2'
            uid: 1501
            password: 'qsdqdqsd'
            state: 'present'
            is_system: True
            remove: True
            skeleton: '/tmp/fake_skel'
            home: '/var/foo'
            shell: '/bin/sh'
            authorized_public_keys: []
            exclusive_public_keys: False
    host_vars: {}
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  options:
    sudo: True
