---

# Role tests

- name: 'Converge | Prerequisites tasks'
  hosts: 'account-management-docker-xenial'
  gather_facts: False
  tasks:
    - name: 'PREREQUISITES | APT | Do an apt-get update'
      become: True
      raw: 'apt-get update -qq'
      changed_when: False
    - name: 'PREREQUISITES | APT | Install python 2.7'
      become: True
      raw: 'apt-get install -qq python2.7'
      changed_when: False


- name: 'Converge | Main tasks'
  hosts: 'all'
  pre_tasks:
    - name: 'Create fake skeleton directories'
      file:
        path: "{{ item }}"
        state: 'directory'
      changed_when: False
      with_items:
        - '/tmp/fake_skel'
        - '/tmp/fake_skel/foo_bar'
    - name: 'Create fake skeleton files'
      file:
        path: "{{ item }}"
        state: 'touch'
      changed_when: False
      with_items:
        - '/tmp/fake_skel/foo.test'
        - '/tmp/fake_skel/foo_bar/.bar.test'
  roles:
    - role: "ansible-role-account-management"
